### ISSUE TITLE
Add to Cart Tranalation

### ISSUE THREAD

**Issue by nmallepally** [Imaginaerum/magento2-language-fr-fr#634] opened 2016-06-17 13:44 UTC
first one is, I have installed the language pack (http://imaginaerum.github.io/magento2-language-fr-fr/en.html)
It works fine, but it does not work on Add to cart button ( when i click on it, it shows Adding and Addedd in english)..  I attaching the image for ref
![adding n added](https://cloud.githubusercontent.com/assets/19605497/16152457/e57d5492-3499-11e6-97ff-1686d0803517.png)

**Comment by stamster** [comment] 2016-06-27 16:01
Also, on Checkout modal / popup page, cart structure is still in English.

**Comment by Imaginaerum** [comment] 2016-07-07 14:04
There is some problems with javascript translations... (Magento bug ?)

**Comment by Imaginaerum** [comment] 2016-07-07 14:47
https://github.com/magento/magento2/issues/4181

**Comment by stamster** [comment] 2016-07-07 15:53
I guess. Thanks for a response @Imaginaerum

**Comment by nmallepally** [comment] 2016-07-12 15:50
Hello Thanks for the updates, but the error messages on website and some check out steps like shipping and review payments are still in English does not translate. and email title to customers
![title email error](https://cloud.githubusercontent.com/assets/19605497/16773688/bc7e87ee-4850-11e6-9e99-804299ba19ff.png)
 as well. attaching images for reference
![checkout english](https://cloud.githubusercontent.com/assets/19605497/16773591/60700e14-4850-11e6-9249-4ffcec27e102.png)
![password not good enought](https://cloud.githubusercontent.com/assets/19605497/16773593/607afd1a-4850-11e6-861f-0c9573482dc2.png)
![remove_from_cart](https://cloud.githubusercontent.com/assets/19605497/16773592/6071d50a-4850-11e6-881c-18eb02d33764.png)

**Comment by quienti** [comment] 2016-07-13 12:12
@nmallepally
What version of Magento are you using ?

Because a lot of translation works well in Magento 2.1!

But for this translate :
https://cloud.githubusercontent.com/assets/19605497/16773593/607afd1a-4850-11e6-861f-0c9573482dc2.png

It's a know issue and 3 pull-requests exist already : https://github.com/magento/magento2/pull/4705

**Comment by nmallepally** [comment] 2016-07-13 12:25
I m using magento 2.0.7 at the moment. So if i do the upgrade will all the above issues work expect the one you mentioned. Is there any way to fix it without upgrade.

Regards,
Navya

**Comment by quienti** [comment] 2016-07-13 12:40
There maybe other problems with translation, I don't know really, because my website is still under development...

I think it is impossible to find all commit to correct all translation in 2.0.7, and edit Magento core is not a good plan.

**Comment by nmallepally** [comment] 2016-07-13 13:21
okay, thank you @quienti . I will plan for the upgrade to fix the bugs. Thank you again.

**Comment by Imaginaerum** [comment] 2016-07-16 07:57
Fixed on last pack version with Magento 2.1.0. Can you try ?

**Comment by stamster** [comment] 2016-07-18 09:03
@Imaginaerum I have updated via composer, and it works fine with 2.1.0.

**Comment by Imaginaerum** [comment] 2016-07-18 09:04
@stamster Thanks a lot.

**Comment by nmallepally** [comment] 2016-07-18 09:06
Thanks @stamster @Imaginaerum I will update to Magento 2.1 and Hopefully it should fix all.

**Comment by stamster** [comment] 2016-07-18 15:46
It will. For me it has fixed it. So the winner is Magento `v2.1.0` and latest `Imaginaerum/magento2-language-fr-fr:*`

**Closed** 2016-07-21 08:21 UTC
Labels: accept

**Comment by nmallepally** [comment] 2016-07-27 12:32
Hi Guys,

I still have translation issues, it fixed few but still has some to be translated.
I have 2.1.0 v and latest imaginaerum installed.

Add to cart still does not translate, shows adding, added and add to cart.
password strength in English
forgot password mail - welcome message in english
 
![password not good enought](https://cloud.githubusercontent.com/assets/19605497/17175242/4406670a-53fe-11e6-9604-caf8ab3d4f32.png)

**Comment by Imaginaerum** [comment] 2016-07-27 12:34
Flush all caches... (For cart only. it's work).
For email: it's a magento bug... It doesn't work... I work for a pull request on Magento repo.

**Comment by quienti** [comment] 2016-07-27 12:58
@Imaginaerum , It already exist a pull request for this https://github.com/magento/magento2/pull/5725/commits/3109c8e96bcd08041f558be65a2a4e3d213d22a4

**Comment by Imaginaerum** [comment] 2016-07-27 13:00
@quienti Thanks ;)

**Comment by nmallepally** [comment] 2016-07-27 14:24
Hi @quienti  I implemented the changes from the pull, now the add to cart does not load and stays static and does not reflect products added to the cart count, remains 0.

**Comment by quienti** [comment] 2016-07-27 15:35
Hmmm , this pull was created by someone who is not a member Magento, so perhaps this pull is wrong, or that you have misapplied this pull...
Do you have an error in the console of the browser?

**Comment by nmallepally** [comment] 2016-07-27 15:40
Hi @quienti  Just reverted back and tested after cleaning all cache..
it works for the first time, when i clear the cache. from the next time i tried to add a product it again shows the translation in English. it is not consistent.

**Comment by quienti** [comment] 2016-07-27 15:48
I had this problem when I was on Magento 2.0, but I never see this problem on Magento 2.1...
On Magento 2.0, this problem was also related to cache browser.
I had completely empty the cache of browser.

I want to try too... Maybe I have not seen...

**Comment by nmallepally** [comment] 2016-07-27 15:50
@quienti Yes, let me know, it works for the first time when i clean my browser cache but later on the second visit, it shows in english.

**Comment by quienti** [comment] 2016-07-27 16:10
![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/17182666/8ed26092-5424-11e6-9d93-f21d0aa0eb3f.jpg)

I am not able to reproduce your problem... It works fine for me.
Do you use a good version of php ? Server ?
Like required here : http://devdocs.magento.com/guides/v2.0/install-gde/bk-install-guide.html#install-verify-prereq

**Comment by nmallepally** [comment] 2016-07-27 16:15
Hi @quienti  I am using php 7.0.9, apache 2.4 and Mysql 5.6(Maria DB), Debian Linux.
I checked again it is not consistent.. checked on various browsers even on mobile, its in English.

**Comment by quienti** [comment] 2016-07-27 16:37
Interesting...
I just tested too from all browser, impossible to produce this problem...

On mobile, I found an another problem with "add to cart", because it is not send with ajax, so, the text do not change (Apparently a bug from Magento)
So, sorry, I do not known why you have a problem who do not exist...

**Comment by nmallepally** [comment] 2016-07-27 21:10
@quienti Okay, thank you for your time. But, it is strange for some reasons it only works for the first time.
If you have time, can you have a look at this issue [#5843](https://github.com/magento/magento2/issues/5843)

**Comment by quienti** [comment] 2016-07-28 07:35
Yes, this is a Magento error, but you can solve this problem after you run this query in your database:
```
ALTER TABLE `sales_invoice_grid`
    ADD COLUMN `base_grand_total` DECIMAL(12,4) NULL DEFAULT NULL COMMENT 'Base Grand Total' AFTER `grand_total`;
```

**Comment by quienti** [comment] 2016-07-28 07:56
For your problem of translation, you have upgrade Magento or this is a fresh install ?

**Comment by nmallepally** [comment] 2016-07-28 07:59
I have done upgrades, from 2.0.4 ->2.0.7->2.1.0.
Its the same now, checked again today , it works when you flush all caches on magento and clean browser cache for first time and then it would stay same in english.

**Comment by stamster** [comment] 2016-07-28 08:30
@nmallepally
I believe your upgrades have messed something. Magento sux when you do upgrades.
On clean install, this translation is fine.

**Comment by nmallepally** [comment] 2016-07-28 08:39
@stamster Okay, i cannot do a fresh install now, as we are heading to production stage now.
Thanks for your time. Let me know if you find any fix.

**Comment by nmallepally** [comment] 2016-07-28 08:43
@quienti thanks for the response on [#5843](https://github.com/magento/magento2/issues/5843#issuecomment-235816637), but it only fixed the invoices page, on Paypal its still an error, it says can't order . I have updated that issue with images, can you look at it, let me know did u find a fix for that. thanks

**Comment by stamster** [comment] 2016-07-28 08:46
I have had many issues with upgrades, as we started dev on v2.0.2. Now we do a clean install first, migrate theme and modules, test everything, and then just abandon old instance. Database does not contain real products yet, so we find this approach the most convininient during development.

**Comment by quienti** [comment] 2016-07-28 08:59
I had started my development on Magento 2.0, and upgraded at every new version.
I never had any problem, just my customs modules who was not compatible with the versions, but after upgraded my codes, nothing else...

Of course, there are new problems from Magento, but nothing very important

**Comment by nmallepally** [comment] 2016-07-28 09:06
@quienti yes, its important for us because the website is for french market, translations are very important. translation does not even work on password strength , welcome messages on order emails too. So, yes its not a major blocking thing, but yet important. Now we have paypal Issue on 2.1.0v. I expected 2.1 v to be clean but now paypal issue again.

**Comment by quienti** [comment] 2016-07-28 09:15
I understand, I'm french and this is important too.
For translation of 'password strength' and 'welcome messages on order emails' are issues known, so there will have a fix in a next version, but, impossible to know what version :/

For Paypal, I do not know, I have not test yet. Have you created a issue for this ?

**Comment by nmallepally** [comment] 2016-07-28 09:18
Yes, I updated here, [#5843](https://github.com/magento/magento2/issues/5843#issuecomment-235746679)

**Comment by nmallepally** [comment] 2016-07-28 09:22
@quienti when i translate the error in English, it says passage not possible. 
![paypal 3 error](https://cloud.githubusercontent.com/assets/19605497/17207566/1eecdbde-54ad-11e6-9339-6dd7094bac0d.png)

**Comment by quienti** [comment] 2016-07-28 09:34
I will try to help you, but see my comment here : https://github.com/magento/magento2/issues/5843#issuecomment-235844330

And comment in your issue, because, this is not the same issue here, so do not mix ;)

**Comment by nmallepally** [comment] 2016-07-28 09:35
okay thanx, i will remove comment here.

**Comment by quienti** [comment] 2016-07-28 09:49
> @quienti Merci l'aide... Il faut voir si il s'agit de problèmes js car c'est une plaie... je vais voir pour remplacer les ' par un caractère spécial.

@Imaginaerum , c'est assez bizarre quand même, j'ai actuellement  2 sites sous Magento 2.1, et j'ai vraiment aucun problème avec cette "Ajout dans le panier"
Pour les ', je connais très bien ce problème, et il est vrai que c'est assez un enfer.
Par contre, je ne sais pas si les caractères spéciaux seront traduit pas js avec le $t ou $.mage._, il faudrait vérifier

**Comment by nmallepally** [comment] 2016-07-28 13:59
@quienti @Imaginaerum Found this translation error on view cart page.
remove confirmation message in english
![translation error](https://cloud.githubusercontent.com/assets/19605497/17215144/cf131624-54d3-11e6-8899-b11dc9659b55.png)

**Comment by quienti** [comment] 2016-07-28 14:20
![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/17215987/1fc2668c-54df-11e6-8d04-e891e76e8638.jpg)

Sorry, but I am not able to produce this problem again :/

**Comment by nmallepally** [comment] 2016-07-28 15:36
Okay @quienti Thanks, but it shows me in English. thanks.

**Comment by nmallepally** [comment] 2016-08-04 13:28
@quienti @Imaginaerum I did even check on fresh install on other domain, it displays few times and it does not. same as the one from upgrade to 2.0.7 to 2.1. Is there any solution to this?.
Is there any commits for password not good enough and welcome email order translation isssues?
